add missing musl_missing.h
	../src/shared/wall.c:53:20: error: '_PATH_UTMPX' undeclared (first use in this function); did you mean 'PATH_MAX'?

Signed-off-by: fossdd <fossdd@pwned.life>